SELECT CART_ID
FROM (SELECT DISTINCT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME = "Milk"
    UNION ALL
    SELECT DISTINCT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME = "Yogurt") AS RESULT_TABLE
GROUP BY CART_ID
HAVING COUNT(NAME) > 1;
