-- 코드를 입력하세요
SELECT B.ANIMAL_ID, B.NAME
    FROM ANIMAL_INS A
    JOIN ANIMAL_OUTS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
        # WHERE (B.DATETIME-A.DATETIME) =
            # (SELECT MAX(B.DATETIME-A.DATETIME)
            #     FROM ANIMAL_INS A
            #     JOIN ANIMAL_OUTS B  
            #     ON A.ANIMAL_ID = B.ANIMAL_ID
            #         GROUP BY B.ANIMAL_ID)
            ORDER BY (B.DATETIME-A.DATETIME) DESC LIMIT 2;