-- 코드를 입력하세요
# SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE, DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1), 1) AS AVERAGE_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY CAR_ID
        HAVING AVERAGE_DURATION >= 7
            ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
    
        