-- 코드를 입력하세요
SELECT 
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH,
    
    COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS,
    ROUND((COUNT(DISTINCT A.USER_ID) /
        (SELECT COUNT(USER_ID)
        FROM USER_INFO
        WHERE JOINED LIKE '2021%')), 1) AS PURCHASED_RATIO
    
FROM USER_INFO A
JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE JOINED LIKE '2021%'
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)