-- 코드를 작성해주세요

WITH RECURSIVE ECOLI AS (

    SELECT ID, PARENT_ID, 1 AS GENERATION
        FROM ECOLI_DATA
            WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT ECOLI2.ID, ECOLI2.PARENT_ID, GENERATION + 1 AS GENERATION
        FROM ECOLI
        JOIN ECOLI_DATA ECOLI2 ON ECOLI.ID = ECOLI2.PARENT_ID
)

SELECT COUNT(ID) AS COUNT, GENERATION
    FROM ECOLI
        WHERE ID NOT IN (SELECT PARENT_ID
                            FROM ECOLI_DATA
                                WHERE PARENT_ID IS NOT NULL
                                    GROUP BY PARENT_ID)
            GROUP BY GENERATION
                ORDER BY GENERATION