WITH RECURSIVE A AS (

    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT B.ID, B.PARENT_ID, GENERATION + 1
    FROM A
    JOIN ECOLI_DATA AS B ON A.ID = B.PARENT_ID
    
)

SELECT 
    COUNT(ID) AS COUNT,
    GENERATION
FROM A
WHERE ID NOT IN
    (SELECT PARENT_ID
        FROM ECOLI_DATA
            WHERE PARENT_ID IS NOT NULL
                GROUP BY PARENT_ID)
GROUP BY GENERATION
ORDER BY GENERATION