SELECT HISTORY_ID,
    CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN
        ROUND((DAILY_FEE * 0.85), 0) * (DATEDIFF(END_DATE, START_DATE)+1)
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN
        ROUND((DAILY_FEE * 0.92), 0) * (DATEDIFF(END_DATE, START_DATE)+1)
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN
        ROUND((DAILY_FEE * 0.95), 0) * (DATEDIFF(END_DATE, START_DATE)+1)
        ELSE DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1) END AS FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
        
        WHERE A.CAR_TYPE = '트럭'
            GROUP BY HISTORY_ID
                ORDER BY FEE DESC, HISTORY_ID DESC;
        