# 대여기록(자동차 종류 = 트럭) 중 대여기록 별 대여 금액

# SELECT A.HISTORY_ID, 
#     CASE WHEN (A.END_DATE-A.START_DATE+1) > 6 THEN TRUNCATE(B.DAILY_FEE * 0.95 * (A.END_DATE-A.START_DATE+1), 0) END AS FEE 
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
# JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON B.CAR_TYPE = C.CAR_TYPE
# WHERE B.CAR_TYPE = '트럭'
# GROUP BY HISTORY_ID;

SELECT A.HISTORY_ID,
    CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90
            THEN ROUND(B.DAILY_FEE * 0.85, 0) * (DATEDIFF(END_DATE, START_DATE)+1)
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30
            THEN ROUND(B.DAILY_FEE * 0.92, 0) * (DATEDIFF(END_DATE, START_DATE)+1)
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7
            THEN ROUND(B.DAILY_FEE * 0.95, 0) * (DATEDIFF(END_DATE, START_DATE)+1)
        ELSE B.DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1) END AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON B.CAR_TYPE = C.CAR_TYPE
WHERE B.CAR_TYPE = '트럭'
GROUP BY A.HISTORY_ID
ORDER BY FEE DESC, A.HISTORY_ID DESC;




# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR;

# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY;

# SELECT *
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN;