-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
    FROM MEMBER_PROFILE A
    JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
        WHERE MEMBER_NAME =
            (SELECT MEMBER_NAME
                FROM MEMBER_PROFILE A
                JOIN REST_REVIEW B  ON A.MEMBER_ID = B.MEMBER_ID
                    GROUP BY B.MEMBER_ID, MEMBER_NAME
                        ORDER BY COUNT(REVIEW_ID) DESC LIMIT 1)
            ORDER BY REVIEW_DATE, REVIEW_TEXT;
    
# SELECT MEMBER_NAME, COUNT(REVIEW_ID)
#     FROM MEMBER_PROFILE A
#     JOIN REST_REVIEW B  ON A.MEMBER_ID = B.MEMBER_ID
#         GROUP BY B.MEMBER_ID, MEMBER_NAME
#             ORDER BY COUNT(REVIEW_ID) DESC;