SELECT B.ID, B.GENOTYPE, A.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA A
JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID AND A.GENOTYPE & B.GENOTYPE = A.GENOTYPE
WHERE B.PARENT_ID IS NOT NULL 
ORDER BY ID;

# SELECT *
# FROM ECOLI_DATA;