-- 코드를 작성해주세요
SELECT B.ID, A.A.FISH_NAME, A.LENGTH
FROM
(SELECT A.FISH_TYPE, B.FISH_NAME, MAX(A.LENGTH) AS LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY A.FISH_TYPE, B.FISH_NAME) A
JOIN FISH_INFO B
WHERE A.LENGTH = B.LENGTH AND A.A.FISH_TYPE = B.FISH_TYPE
ORDER BY ID


