-- 코드를 작성해주세요

SELECT CASE WHEN ID IN
    (SELECT ID
        FROM SKILLCODES A
        JOIN DEVELOPERS B
        WHERE B.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AND
        (B.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End')))
        THEN 'A'
    WHEN ID IN 
        (SELECT ID
        FROM SKILLCODES A
        JOIN DEVELOPERS B
        WHERE B.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#'))
        THEN 'B'
    WHEN ID IN
        (SELECT ID
        FROM SKILLCODES A
        JOIN DEVELOPERS B
        WHERE (B.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End')))
        THEN 'C' 
    END AS GRADE, ID, EMAIL
    FROM SKILLCODES A
    JOIN DEVELOPERS B
        GROUP BY GRADE, ID, EMAIL
            HAVING GRADE IS NOT NULL
                ORDER BY GRADE, ID
# A
# (SELECT *
#     FROM SKILLCODES A
#     JOIN DEVELOPERS B
#         WHERE B.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AND
#             (B.SKILL_CODE & A.CODE) IN (SELECT CODE FROM SKILLCODES WHERE CATEGORY = 'Front End'))

# B
# (SELECT *
#     FROM SKILLCODES A
#     JOIN DEVELOPERS B
#         WHERE B.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#'))

# C
# (SELECT 
#     FROM SKILLCODES A
#     JOIN DEVELOPERS B
#         WHERE (B.SKILL_CODE & A.CODE) IN (SELECT CODE FROM SKILLCODES WHERE CATEGORY = 'Front End'))
